export declare type Asset = {
    id: number;
    filename: string;
    space_id: number;
    created_at: string;
    updated_at: string;
    asset_folder_id: number;
    deleted_at?: string;
    content_length: number;
    content_type: string;
    alt: string;
    copyright: string;
    title: string;
    focus?: string;
    ext_id?: number;
    expire_at?: string;
    source?: string;
    internal_tag_ids: string[];
    locked: boolean;
    is_private: boolean;
    publish_at?: string;
    internal_tags_list: string[];
    short_filename: string;
};
export declare function GetAssets(): Promise<Asset[]>;
export declare function GetAsset(assetId: number): Promise<Asset>;
export declare function UpdateAsset(assetId: number, asset: Partial<Asset>): Promise<Asset>;
